---
# Install tasks for CentOS
- name: install required software
  include_role:
    name: amtega.packages
  vars:
    packages_os:
      centos:
        all:
          docker-io: present
          libselinux-python: present
    packages_python:
      all:
        all:
          - name: dockerpy
            state: absent

          - name: docker
            state: present

          - name: requests
            state: present
    tags:
      - skip-lint
