---
# Install tasks common to all distros

- block:
    - name: remove obsolete docker packages
      package:
        name: "{{ item }}"
        state: absent
      loop: >-
        {{ docker_engine_obsolete_packages[distro_packages_key] }}
      tags:
        - role::docker_engine
        - role::docker_engine::packages
        - role::docker_engine::install

    - name: install docker packages
      package:
        name: "{{ item }}"
        state: present
      loop: >-
        {{ docker_engine_packages[distro_packages_key] }}
      notify:
        - restart docker
        - restart docker storage

    - name: create directory for http/https proxy config file in systemd
      file:
        path: "{{ docker_engine_systemd_proxy_config | dirname }}"
        state: directory
        owner: root
        group: root
        mode: 0755
      when:
        - ansible_facts.service_mgr == "systemd"
        - >-
          docker_engine_http_proxy | default('') | length > 0
          or docker_engine_https_proxy | default('') | length > 0
          or docker_engine_no_proxy | default('') | length > 0
      notify:
        - restart docker
        - restart docker storage
  vars:
    distro_packages_key: >-
      {{ ansible_facts.distribution
         | lower
         + "_" + ansible_facts.distribution_major_version }}
  tags:
    - role::docker_engine
    - role::docker_engine::packages
    - role::docker_engine::install
