---
# Install tasks common to all distros

- block:
    - name: create directory for local socket
      file:
        path: "{{ docker_engine_socket | dirname }}"
        state: directory
        owner: root
        group: root
        mode: 0755
      when: docker_engine_socket | length > 0

    - name: create directory for http/https proxy config file in systemd
      file:
        path: "{{ docker_engine_systemd_proxy_config | dirname }}"
        state: directory
        owner: root
        group: root
        mode: 0755
      when:
        - ansible_facts.service_mgr == "systemd"
        - >-
          proxy_client_http_proxy | default('') | length > 0
          or proxy_client_https_proxy | default('') | length > 0
          or proxy_client_no_proxy | default('') | length > 0

    - name: remove obsolete daemon config file
      file:
        path: "{{ docker_engine_daemon_config }}"
        state: absent
  tags:
    - role::docker_engine
    - role::docker_engine::packages
    - role::docker_engine::install
