---
# Install tasks common to all distros

- block:
    - name: Create directory for local socket
      file:
        path: "{{ docker_engine_socket | dirname }}"
        state: directory
        owner: root
        group: root
        mode: 0755
      when: docker_engine_socket | length > 0

    - name: Create directories for docker config
      file:
        path: "{{ item }}"
        state: directory
        owner: root
        group: root
        mode: 0755
      with_items:
        - "{{ docker_engine_daemon_config_dir }}"
        - "{{ docker_engine_systemd_service_config_dir }}"

    - name: Create a conf file in systemd to override daemon conf with daemon.json
      copy:
        dest: "{{ docker_engine_systemd_service_config }}"
        content: |
          [Service]
          ExecStart=
          ExecStart=/usr/bin/dockerd --containerd=/run/containerd/containerd.sock

    - name: Create directory for http/https proxy config file in systemd
      file:
        path: "{{ docker_engine_systemd_proxy_config | dirname }}"
        state: directory
        owner: root
        group: root
        mode: 0755
      when:
        - ansible_facts.service_mgr == "systemd"
        - >-
          proxy_client_http_proxy | default('') | length > 0
          or proxy_client_https_proxy | default('') | length > 0
          or proxy_client_no_proxy | default('') | length > 0

  tags:
    - role::docker_engine
    - role::docker_engine::packages
    - role::docker_engine::install
