---
# Install tasks common to all distros

- block:
    - name: remove obsolete docker packages
      package:
        name: "{{ item }}"
        state: absent
      with_items: >-
        {{ obsolete_docker_engine_packages[ansible_os_family | lower]
           | default([]) }}
      tags:
        - role::docker_engine
        - role::docker_engine::packages
        - role::docker_engine::install

    - name: install docker packages
      package:
        name: "{{ item }}"
        state: present
      with_items: >-
        {{ docker_engine_packages[ansible_os_family | lower]
           | default([]) }}
  tags:
    - role::docker_engine
    - role::docker_engine::packages
    - role::docker_engine::install
