---
# Install tasks for debian

- block:
    - name: add gpg key for docker repository in apt
      apt_key:
        url: https://download.docker.com/linux/debian/gpg
        state: present

    - apt_repository:
        repo: >-
            deb
            https://download.docker.com/linux/{{ ansible_distribution | lower }}
            {{ ansible_distribution_release }} stable
        state: present
        filename: "docker"
  tags:
    - role::docker_engine
    - role::docker_engine::packages
    - role::docker_engine::install
