---
# Install tasks for debian

- block:
    - name: Add https support to apt
      package:
        name: apt-transport-https
        state: present

    - name: Add gpg key for docker repository in apt
      apt_key:
        url: https://download.docker.com/linux/debian/gpg
        state: present

    - name: Add docker repository
      apt_repository:
        repo: >-
            deb
            https://download.docker.com/linux/{{ ansible_facts.distribution
                                                 | lower }}
            {{ ansible_facts.distribution_release }} stable
        state: present
        filename: docker

    - name: Install docker-ce package
      package:
        name: docker-ce
        state: present
  tags:
    - role::docker_engine
    - role::docker_engine::packages
    - role::docker_engine::install
