---
# Install tasks for Fedora
- block:
    - name: install required software
      include_role:
        name: amtega.packages
      vars:
        packages_os:
          fedora:
            all:
              docker-io: present
              libselinux-python: present
        packages_python:
          all:
            all:
              - name: dockerpy
                state: absent

              - name: docker
                state: present

              - name: requests
                state: present

  when: ansible_facts.distribution_version is version('30', '<=')
  tags:
    - skip-lint


- block:
    - name: set up docker respository
      yum_repository:
        name: docker-ce
        baseurl: "https://download.docker.com/linux/fedora/{{ ansible_facts.distribution_major_version }}/x86_64/stable"
        description: Docker repository
        state: present
        gpgcheck: no
        enabled: yes
      notify:
        - reboot host
        - wait host

    - name: Adjust kernel params to cgroups v1 compatibility
      include_role:
        name: amtega.grub_options
      vars:
        grub_options_present:
          - "systemd.unified_cgroup_hierarchy=0"

    - name: Install requires packages
      include_role:
        name: amtega.packages
      vars:
        packages_os:
          fedora:
            all:
              docker-ce: present
        packages_python:
          all:
            all:
              - name: dockerpy
                state: absent

              - name: docker
                state: present

              - name: requests
                state: present

    - name: reboot if necesary
      meta: flush_handlers
  when: ansible_facts.distribution_version is version('31', '>=')
  tags:
    - skip-lint
