---
# Install tasks

- block:
    - include_tasks: "{{ role_path }}/tasks/install/docker-ce.yml"
    - include_tasks: "{{ role_path }}/tasks/install/common.yml"
  tags:
    - role::docker_engine
    - role::docker_engine::packages
    - role::docker_engine::install
