---
# Install tasks for all operating systems

- name: install docker packages
  package:
    name: "{{ item }}"
    state: present
  with_items: >
    {{ docker_engine_packages | default([]) }}
  tags:
    - role::docker_engine
    - role::docker_engine::packages
    - role::docker_engine::install
