---
# Install tasks

- block:
  - apt_repository:
      repo: >-
          deb
          https://download.docker.com/linux/{{ ansible_distribution | lower }}
          {{ ansible_distribution_release }} stable
      state: present
      filename: "docker"

  - name: add gpg key for docker repository in apt
    apt_key:
      url: https://download.docker.com/linux/debian/gpg
      state: present
  when: ansible_os_family == "Debian"

- name: remove obsolete docker packages
  package:
    name: "{{ item }}"
    state: absent
  with_items: >-
    {{ obsolete_docker_engine_packages[ansible_os_family | lower]
       | default([]) }}
  tags:
    - role::docker_engine
    - role::docker_engine::packages
    - role::docker_engine::install

- name: install docker packages
  package:
    name: "{{ item }}"
    state: present
  with_items: >-
    {{ docker_engine_packages[ansible_os_family | lower]
       | default([]) }}
  tags:
    - role::docker_engine
    - role::docker_engine::packages
    - role::docker_engine::install
