---
# Install tasks

- block:
    - include_tasks: >-
        {{ role_path }}/tasks/install_{{ ansible_os_family | lower }}.yml

    - include_tasks: "{{ role_path }}/tasks/install_common.yml"
  tags:
    - role::docker_engine
    - role::docker_engine::packages
    - role::docker_engine::install
