---

- name: Setup kernel for docker
  block:
    - ansible.builtin.include_tasks: grub.yml

    - name: Trigger reboot to apply kernel options changes
      ansible.builtin.command: /bin/true
      notify:
        - reboot host
        - wait host
      when:
        - ansible_facts.distribution_version is version('31', '>=')
        - grub_options_add_result is changed

    - name: Flush handlers
      ansible.builtin.meta: flush_handlers
  tags:
    - role::docker_engine
    - role::docker_engine::install
    - role::docker_engine::install::kernel
