---
# Role tasks

- name: include specific operating system variables
  include: include/os_vars.yml

- name: run folder with specific operating system tasks
  include: include/os_tasks.yml
  with_items:
    - install
    - configure
    - service
  loop_control:
    loop_var: folder
