---
# Role tasks

- name: launch install tasks
  include: tools/os_tasks.yml folder=install
  static: false
  tags:
    - role::docker_engine
    - role::docker_engine::install

- name: launch configure tasks
  include: tools/os_tasks.yml folder=configure
  static: false
  tags:
    - role::docker_engine
    - role::docker_engine::configure

- name: launch configure tasks
  include: tools/os_tasks.yml folder=service
  static: false
  tags:
    - role::docker_engine
    - role::docker_engine::service
