---

- ansible.builtin.include_tasks: repo.yml
  tags:
    - role::docker_engine
    - role::docker_engine::install
    - role::docker_engine::install::repo

- ansible.builtin.include_tasks: kernel.yml
  tags:
    - role::docker_engine
    - role::docker_engine::install
    - role::docker_engine::install::kernel

- ansible.builtin.include_tasks: packages.yml
  tags:
    - role::docker_engine
    - role::docker_engine::install
    - role::docker_engine::install::packages

- ansible.builtin.include_tasks: daemon.yml
  tags:
    - role::docker_engine
    - role::docker_engine::configure
    - role::docker_engine::configure::daemon

- ansible.builtin.include_tasks: users.yml
  tags:
    - role::docker_engine
    - role::docker_engine::configure
    - role::docker_engine::configure::users

- ansible.builtin.include_tasks: service.yml
  tags:
    - role::docker_engine
    - role::docker_engine::service

- ansible.builtin.include_tasks: registry.yml
  tags:
    - role::docker_engine
    - role::docker_engine::registry
