---
# Role tasks

- name: install docker engine
  include: install.yml
  static: false
  tags:
    - role::docker_engine
    - role::docker_engine::install

- name: configure docker engine
  include: configure.yml
  static: false
  tags:
    - role::docker_engine
    - role::docker_engine::configure

- name: setup docker engine service
  include: service.yml
  static: false
  tags:
    - role::docker_engine
    - role::docker_engine::service
