---
# Role tasks

- name: Run role dependencies
  include_tasks: common/dependencies.yml
  tags:
    - role::docker_engine
    - role::docker_engine::install
    - role::docker_engine::configure
    - role::docker_engine::service

- name: Install docker engine
  include_tasks: install/main.yml
  tags:
    - role::docker_engine
    - role::docker_engine::install

- name: Configure docker engine
  include_tasks: configure/main.yml
  tags:
    - role::docker_engine
    - role::docker_engine::configure

- name: Put docker engine into service
  include_tasks: service/main.yml
  tags:
    - role::docker_engine
    - role::docker_engine::service
