---
# Role tasks

- name: sanity checks
  import_tasks: check/main.yml
  tags:
    - role::docker_engine
    - role::docker_engine::check

- name: install docker engine
  include_tasks: install/main.yml
  tags:
    - role::docker_engine
    - role::docker_engine::install

- name: configure docker engine
  include_tasks: configure/main.yml
  tags:
    - role::docker_engine
    - role::docker_engine::configure

- name: put docker engine into service
  include_tasks: service/main.yml
  tags:
    - role::docker_engine
    - role::docker_engine::service
