---
# Role tasks

- name: install docker engine
  include_tasks: install.yml
  tags:
    - role::docker_engine
    - role::docker_engine::install

- name: configure docker engine
  include_tasks: configure.yml
  tags:
    - role::docker_engine
    - role::docker_engine::configure

- name: setup docker engine service
  include_tasks: service.yml
  tags:
    - role::docker_engine
    - role::docker_engine::service
