---
# Role tasks

- name: install docker engine
  include_tasks: install/main.yml
  tags:
    - role::docker_engine
    - role::docker_engine::install

- name: configure docker engine
  include_tasks: configure/main.yml
  tags:
    - role::docker_engine
    - role::docker_engine::configure
