---
# Include OS specific vars

- name: include os specific variables
  include_vars: '{{ item }}'
  with_first_found:
   - files:
       - '{{ ansible_distribution | lower }}.yml'
       - default.yml
     paths:
       - defaults
  tags:
    - role::docker_engine
