---

- name: Setup docker registry
  block:
    - name: Start docker registry container
      docker_container:
        name: "{{ docker_engine_registry_container_name }}"
        state: "{{ docker_engine_registry_state }}"
        image: "{{ docker_engine_registry_image }}"
        exposed:
          - "5000"
        ports:
          - "{{ docker_engine_registry_port }}:5000"
        restart_policy: always
        container_default_behavior: no_defaults
      register: docker_engine_start_registry

    - name: Get docker registry ip address
      ansible.builtin.shell: >-
        docker inspect --format='{''{.NetworkSettings.IPAddress}''}'
        {{ docker_engine_registry_container_name }}
      register: docker_engine_search_registry_ip_result
      when: docker_engine_registry_state in ["present", "started"]
      changed_when: no

    - name: Setup registries config directory
      ansible.builtin.file:
        path: "{{ docker_engine_registries_conf_path | dirname }}"
        state: directory
        owner: root
        group: root
        mode: 0644

    - name: Setup docker registries
      ansible.builtin.template:
        src: registries.conf.j2
        dest: "{{ docker_engine_registries_conf_path }}"
        owner: root
        group: root
        mode: 0644
      vars:
        registries: "{{ docker_engine_registries }}"
        insecure: >-
          {{ (docker_engine_registry_state in ["present", "started"])
             | ternary(docker_engine_insecure_registries
                       + [ docker_engine_search_registry_ip_result.stdout
                           | default("localhost")
                           + ":5000" ],
                       docker_engine_insecure_registries) }}
        blocked: "{{ docker_engine_blocked_registries }}"
      notify:
        - restart docker
  tags:
    - role::docker_engine
    - role::docker_engine::registry
