---
# Tasks to setup docker engine service

- block:

  - name: enable docker service
    service:
      name: docker
      enabled: yes

  - name: start docker
    service:
      name: docker
      state: started

  tags:
    - role::docker_engine
    - role::docker_engine::service
