---

- name: Setup docker users
  block:
    - name: Ensure docker group is present
      ansible.builtin.group:
        name: docker
        state: present
        system: yes

    - name: Add users into docker group
      ansible.builtin.user:
        append: yes
        groups: docker
        state: present
        name: "{{ item }}"
      loop: "{{ docker_engine_users | default([]) }}"
  tags:
    - role::docker_engine
    - role::docker_engine::configure
    - role::docker_engine::configure::users
