---
# Run os specific taks within a folder

- name: run folder tasks applicable to all operating systems
  include: "{{ role_path }}/tasks/{{ folder }}/main.yml"

- name: run folder specific operating system tasks
  include: "{{ file }}"
  with_first_found:
   - files:
       - "{{ ansible_distribution | lower }}.yml"
     paths:
       - "{{ role_path }}/tasks/{{ folder }}"
     skip: true
  loop_control:
    loop_var: file
