---
# Role handlers

- name: Setup docker service
  ansible.builtin.service:
    name: docker
    enabled: yes
    state: restarted
  listen: restart docker
  tags:
    - role::docker_engine
    - role::docker_engine::service
