---
# Role handlers

- name: Docker_engine restart service
  include_tasks: common/docker_service.yml
  vars:
    docker_engine_service_state: restarted
  listen: restart docker
  tags:
    - role::docker_engine
    - role::docker_engine::service
