---

- name: Verify
  hosts: molecule_hosts
  gather_facts: no
  become: yes
  tasks:
    - meta: flush_handlers

    - name: Get docker info
      command: docker info
      register: docker_info_result
      changed_when: false

    - name: Verify docker info
      assert:
        that: >-
          {{ docker_info_result.stdout is search("Server Version")
             or docker_info_result.stdout is search("Storage Driver") }}

    - name: Check docker listen options
      wait_for:
        port: 2375
        timeout: 15

    - name: Check docker registry service
      wait_for:
        port: 5000
        timeout: 60
        connect_timeout: 5
