---
# Docker storage service tasks

- name: setup docker storage service
  service:
    name: docker-storage-setup
    state: "{{ docker_engine_storage_service_state }}"
    enabled: >-
      {{ docker_engine_storage_driver | length != 0
         and docker_engine_storage_service_state == "started" }}
  when:
    - ansible_facts.distribution | lower in ["centos", "fedora", "rhel"]
    - ansible_facts.distribution_version is version('7', '>=')
    - docker_engine_config_storage_result is defined
    - docker_engine_config_storage_result is changed
  vars:
    docker_engine_storage_service_state: >-
      {{ (docker_engine_service_state is undefined)
         | ternary(
             (ansible_facts.distribution | lower in ["centos", "fedora", "rhel"]
              and ansible_facts.distribution_version is version('7', '>='))
              | ternary("started", "stopped"),
             docker_engine_service_state) }}
  tags:
    - role::docker_engine
    - role::docker_engine::service
