---
# Configuration tasks common to all distros

- block:

  - name: ensure "docker" group is present
    group:
      name: docker
      state: present
      system: yes

  - name: add users into "docker" group
    user:
      append: yes
      groups: docker
      state: present
      name: '{{ item }}'
    with_items: "{{ docker_engine_users | default([]) }}"

  tags:
    - role::docker_engine
    - role::docker_engine::configure
