---
# Configuration tasks common to all distros

- block:
    - name: Ensure docker group is present
      group:
        name: docker
        state: present
        system: yes

    - name: Add users into docker group
      user:
        append: yes
        groups: docker
        state: present
        name: "{{ item }}"
      loop: "{{ docker_engine_users | default([]) }}"

    - block:
        - name: Read docker systemd unit file
          command: "cat {{ docker_engine_systemd_service[distro_key] }}"
          register: docker_engine_read_systemd_result
          changed_when: no

        - name: Fix docker systemd unit file
          lineinfile:
            path: "{{ docker_engine_systemd_service[distro_key] }}"
            regexp: "^Requires=(.*)$"
            line: "Requires={{ docker_engine_requires }}"
            backrefs: yes
            state: present
          register: docker_engine_fix_systemd_result
          vars:
            docker_engine_requires: >-
              {{ ((docker_engine_read_systemd_result.stdout_lines
                  | select("search", "^Requires=.*")
                  | list
                  | first
                  | regex_replace("^Requires=", "")).split(" ")
                  + [ "network.service" ])
                 | unique
                 | join(" ") }}

        - name: Reload systemd
          systemd:
            daemon_reload: yes
          when: docker_engine_fix_systemd_result is changed
      vars:
        distro_key: >-
          {{ ansible_facts.distribution
             | lower
             + "_" + ansible_facts.distribution_major_version }}

    - name: Create http/https proxy config file for systemd service
      template:
        src: systemd_http_proxy.j2
        dest: "{{ docker_engine_systemd_proxy_config }}"
        owner: root
        group: root
        mode: 0644
      register: create_systemd_proxy_config_result
      notify:
        - restart docker
        - restart docker storage
      when:
        - ansible_facts.service_mgr == "systemd"
        - >-
          proxy_client_http_proxy | default("") | length > 0
          or proxy_client_https_proxy | default("") | length > 0
          or proxy_client_no_proxy | default("") | length > 0

    - name: Reload systemd to apply new http/https config file
      command: systemctl daemon-reload
      args:
        warn: no
      when:
        - ansible_facts.service_mgr == "systemd"
        - create_systemd_proxy_config_result is changed
  tags:
    - role::docker_engine
    - role::docker_engine::configure
