---
# Configuration tasks for all operating systems

- block:

  - name: ensure "docker" group is present
    group:
      name: docker
      state: present
      system: yes

  - name: add users into "docker" group
    user:
      append: yes
      groups: docker
      state: present
      name: '{{ item }}'
    with_items: >
      {{ docker_engine_users | default([]) }}

  - name: "configure docker storage"
    template:
      src: docker_storage.template.j2
      dest: "/etc/sysconfig/docker-storage"
      owner: root
      group: root
      mode: 0644
      backup: no

  tags:
    - role::docker_engine
    - role::docker_engine::configure
