---
# Configuration tasks for Red Hat
- block:

    - name: Configure docker daemon
      template:
        src: docker_daemon.j2
        dest: "{{ docker_engine_daemon_config_dir }}/daemon.json"
        owner: root
        group: root
        mode: 0644
        backup: no
      notify:
        - restart docker

  tags:
    - role::docker_engine
    - role::docker_engine::configure
