---
# Run os specific tasks within a folder

- name: run tasks applicable to all operating systems
  include: "{{ role_path }}/tasks/{{ folder }}/main.yml"

- name: search specific operating system tasks
  find:
    paths: "{{ role_path }}/tasks/{{ folder }}"
    patterns: "*{{ ansible_distribution | lower }}*.yml"
  register: search_folder_tasks_result
  tags:
    - always

- name: run specific operating system tasks
  include: "{{ file.path }}"
  with_items: "{{ search_folder_tasks_result.files | sort(attribute='path') }}"
  loop_control:
    loop_var: file
