---
# Role check tasks

- block:
    - name: assert platform is supported
      assert:
        that:
          - distribution in docker_engine_supported_distributions
          - >-
            ansible_facts.distribution_version
            is version(docker_engine_supported_versions[distribution], ">=")
      vars:
        distribution: "{{ ansible_facts.distribution | lower }}"
  tags:
    - role::tomcat
    - role::tomcat::check
