---
# Service tasks

- block:
    - include_tasks: "{{ service_playbook }}"
      vars:
        service_playbook: >-
          {{ role_path }}/tasks/service/{{ ansible_os_family | lower }}.yml

    - include_tasks: "{{ role_path }}/tasks/service/common.yml"
  tags:
    - role::docker_engine
    - role::docker_engine::service
