---
# Service tasks for Red Hat

- block:
    - name: enable docker storage setup service
      service:
        name: docker-storage-setup
        enabled: yes

    - name: start docker storage setup service
      service:
        name: docker-storage-setup
        state: started
      when: docker_engine_storage_driver | length != 0

    - name: stop docker storage setup service
      service:
        name: docker-storage-setup
        state: stopped
      when: docker_engine_storage_driver | length == 0
  when: ansible_distribution_version | version_compare('7', '>=')
  tags:
    - role::docker_engine
    - role::docker_engine::service
